In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
import numpy as np
from pylab import rcParams
from pylab import savefig

import scipy
from scipy import stats

from scipy.stats.stats import pearsonr
from scipy.stats import spearmanr
from scipy.stats import chi2_contingency

In [2]:
address = '~/Desktop/code/hrdata.csv'
hr = pd.read_csv(address)

In [3]:
print(hr.head(10))
print(hr.describe())

          Employee Name  Employee Number State     Zip         DOB   Age  \
0            Brown, Mia     1.103024e+09    MA  1450.0  11/24/1985  32.0
1  LaRotonda, William       1.106027e+09    MA  1460.0   4/26/1984  33.0
2      Steans, Tyrone       1.302053e+09    MA  2703.0    9/1/1986  31.0
3       Howard, Estelle     1.211051e+09    MA  2170.0   9/16/1985  32.0
4           Singh, Nan      1.307060e+09    MA  2330.0   5/19/1988  29.0
5      Smith, Leigh Ann     7.110077e+08    MA  1844.0   6/14/1987  30.0
6   LeBlanc, Brandon  R     1.102024e+09    MA  1460.0   6/10/1984  33.0
7           Quinn, Sean     1.206043e+09    MA  2045.0   11/6/1984  33.0
8     Boutwell, Bonalyn     1.307060e+09    MA  2468.0    4/4/1987  30.0
9     Foster-Baker, Amy     1.201031e+09    MA  2050.0   4/16/1979  38.0

      Sex MaritalDesc          CitizenDesc Hispanic/Latino  \
0  Female     Married           US Citizen              No
1    Male    Divorced           US Citizen              No
2    Male      Single           US Citizen              No
3  Female     Married           US Citizen              No
4  Female      Single           US Citizen              No
5  Female     Married           US Citizen              No
6    Male     Married           US Citizen              No
7    Male     Married  Eligible NonCitizen              No
8  Female     Married           US Citizen              No
9  Female     Married           US Citizen              no

             ...            Date of Hire Date of Termination  \
0            ...              10/27/2008                 NaN
1            ...                1/6/2014                 NaN
2            ...               9/29/2014                 NaN
3            ...               2/16/2015           4/15/2015
4            ...                5/1/2015                 NaN
5            ...               9/26/2011           9/25/2013
6            ...                1/5/2016                 NaN
7            ...               2/21/2011           8/15/2015
8            ...               2/16/2015                 NaN
9            ...                1/5/2009                 NaN

        Reason For Term       Employment Status     Department  \
0  N/A - still employed                  Active  Admin Offices
1  N/A - still employed                  Active  Admin Offices
2  N/A - still employed                  Active  Admin Offices
3  N/A - still employed                  Active  Admin Offices
4  N/A - still employed                  Active  Admin Offices
5         career change  Voluntarily Terminated  Admin Offices
6  N/A - still employed                  Active  Admin Offices
7         career change  Voluntarily Terminated  Admin Offices
8  N/A - still employed                  Active  Admin Offices
9  N/A - still employed                  Active  Admin Offices

                   Position Pay Rate        Manager Name  \
0              Accountant I    28.50  Brandon R. LeBlanc
1              Accountant I    23.00  Brandon R. LeBlanc
2              Accountant I    29.00  Brandon R. LeBlanc
3  Administrative Assistant    21.50  Brandon R. LeBlanc
4  Administrative Assistant    16.56  Brandon R. LeBlanc
5  Administrative Assistant    20.50  Brandon R. LeBlanc
6   Shared Services Manager    55.00          Janet King
7   Shared Services Manager    55.00          Janet King
8            Sr. Accountant    34.95  Brandon R. LeBlanc
9            Sr. Accountant    34.95  Board of Directors

          Employee Source         Performance Score
0      Diversity Job Fair               Fully Meets
1      Website Banner Ads               Fully Meets
2         Internet Search               Fully Meets
3  Pay Per Click - Google  N/A- too early to review
4      Website Banner Ads  N/A- too early to review
5      Diversity Job Fair               Fully Meets
6             Monster.com               Fully Meets
7      Diversity Job Fair               Fully Meets
8      Diversity Job Fair              90-day meets
9                   Other               Fully Meets

[10 rows x 21 columns]
       Employee Number           Zip         Age    Pay Rate
count     3.010000e+02    301.000000  301.000000  301.000000
mean      1.205421e+09   6705.196013   38.548173   30.715249
std       1.826616e+08  17167.527864    8.942884   15.216214
min       6.020003e+08   1013.000000   25.000000   14.000000
25%       1.102024e+09   1901.000000   31.000000   20.000000
50%       1.204033e+09   2132.000000   37.000000   24.000000
75%       1.401065e+09   2421.000000   44.000000   43.000000
max       1.988300e+09  98052.000000   67.000000   80.000000

In [4]:
hr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 21 columns):
Employee Name          301 non-null object
Employee Number        301 non-null float64
State                  301 non-null object
Zip                    301 non-null float64
DOB                    301 non-null object
Age                    301 non-null float64
Sex                    301 non-null object
MaritalDesc            301 non-null object
CitizenDesc            301 non-null object
Hispanic/Latino        301 non-null object
RaceDesc               301 non-null object
Date of Hire           301 non-null object
Date of Termination    103 non-null object
Reason For Term        301 non-null object
Employment Status      301 non-null object
Department             301 non-null object
Position               301 non-null object
Pay Rate               301 non-null float64
Manager Name           301 non-null object
Employee Source        301 non-null object
Performance Score      301 non-null object
dtypes: float64(4), object(17)
memory usage: 49.6+ KB

In [5]:
hr.corr()

                 Employee Number       Zip       Age  Pay Rate
Employee Number         1.000000  0.124567  0.161245  0.019012
Zip                     0.124567  1.000000 -0.013362  0.412814
Age                     0.161245 -0.013362  1.000000  0.016798
Pay Rate                0.019012  0.412814  0.016798  1.000000

In [6]:
hr.max()

Employee Name                      Zima, Colleen
Employee Number                       1.9883e+09
State                                         WA
Zip                                        98052
DOB                                     9/9/1965
Age                                           67
Sex                                         male
MaritalDesc                              widowed
CitizenDesc                           US Citizen
Hispanic/Latino                              yes
RaceDesc                                   White
Date of Hire                            9/6/2011
Date of Termination                     9/7/2015
Reason For Term                          unhappy
Employment Status         Voluntarily Terminated
Department             Software Engineering
Position                    Sr. Network Engineer
Pay Rate                                      80
Manager Name                      Webster Butler
Employee Source                    Word of Mouth
Performance Score                            PIP
dtype: object

In [8]:
hr.isnull()

,Employee Name,Employee Number,State,Zip,DOB,Age,Sex,MaritalDesc,CitizenDesc,Hispanic/Latino,...,Date of Hire,Date of Termination,Reason For Term,Employment Status,Department,Position,Pay Rate,Manager Name,Employee Source,Performance Score
0,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
273,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
274,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
275,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
276,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
277,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
278,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
279,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
280,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
281,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
282,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
283,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
284,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
285,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
286,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
287,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
288,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
289,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
290,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
291,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
292,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
293,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
294,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
295,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
296,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
297,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
298,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
299,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
300,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
301,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [9]:
hr.count()

Employee Name          301
Employee Number        301
State                  301
Zip                    301
DOB                    301
Age                    301
Sex                    301
MaritalDesc            301
CitizenDesc            301
Hispanic/Latino        301
RaceDesc               301
Date of Hire           301
Date of Termination    103
Reason For Term        301
Employment Status      301
Department             301
Position               301
Pay Rate               301
Manager Name           301
Employee Source        301
Performance Score      301
dtype: int64

In [10]:
hr['terminated']=hr['Date of Termination'].fillna(0)

In [11]:
hr['terminated']=np.where(hr['terminated']!=0, 1, 0)
hr['terminated'].head(10)

0    0
1    0
2    0
3    1
4    0
5    1
6    0
7    1
8    0
9    0
Name: terminated, dtype: int64

In [12]:
hr.groupby('terminated').mean()

            Employee Number          Zip        Age   Pay Rate
terminated
0              1.213154e+09  8500.631313  37.939394  32.645556
1              1.190557e+09  3253.776699  39.718447  27.004563

In [13]:
hr.groupby('terminated').describe()

              Age                                                     \
            count       mean       std   min   25%   50%   75%   max
terminated
0           198.0  37.939394  8.434662  25.0  31.0  36.0  43.0  67.0
1           103.0  39.718447  9.783357  26.0  32.0  38.0  45.0  66.0

           Employee Number                 ...    Pay Rate          Zip  \
                     count          mean   ...         75%   max  count
terminated                                 ...
0                    198.0  1.213154e+09   ...        53.0  80.0  198.0
1                    103.0  1.190557e+09   ...        29.0  62.0  103.0

                                                                        \
                   mean           std     min     25%     50%      75%
terminated
0           8500.631313  20534.854650  1013.0  1893.0  2132.5  2428.25
1           3253.776699   5841.834197  1420.0  1901.5  2129.0  2390.00


                max
terminated
0           98052.0
1           43050.0

[2 rows x 32 columns]

In [14]:
table = pd.crosstab(hr['terminated'], hr['Pay Rate'])
chi2, p, dof, expected = chi2_contingency(table.values)
print('Chi-square Statistic %0.3f p_value %0.3f' % (chi2, p))
#No sig. ass'n b/w termination and pay rate

Chi-square Statistic 98.452 p_value 0.254

In [15]:
table = pd.crosstab(hr['Zip'], hr['Pay Rate'])
chi2, p, dof, expected = chi2_contingency(table.values)
print('Chi-square Statistic %0.3f p_value %0.3f' % (chi2, p))
#No sig. ass'n b/w zip code and pay rate

Chi-square Statistic 13423.032 p_value 1.000

In [16]:
hr_trim = hr[['Pay Rate', 'Performance Score', 'Sex', 'Age', 'terminated', 'Employee Source']]

In [17]:
hr_trim.head(10)

,Pay Rate,Performance Score,Sex,Age,terminated,Employee Source
0,28.50,Fully Meets,Female,32.0,0,Diversity Job Fair
1,23.00,Fully Meets,Male,33.0,0,Website Banner Ads
2,29.00,Fully Meets,Male,31.0,0,Internet Search
3,21.50,N/A- too early to review,Female,32.0,1,Pay Per Click - Google
4,16.56,N/A- too early to review,Female,29.0,0,Website Banner Ads
5,20.50,Fully Meets,Female,30.0,1,Diversity Job Fair
6,55.00,Fully Meets,Male,33.0,0,Monster.com
7,55.00,Fully Meets,Male,33.0,1,Diversity Job Fair
8,34.95,90-day meets,Female,30.0,0,Diversity Job Fair
9,34.95,Fully Meets,Female,38.0,0,Other

In [18]:
hr_trim = pd.get_dummies(hr_trim, columns=['Performance Score', 'Sex', 'Employee Source'])

In [22]:
hr_trim.head()
hr_trim[['Sex']]

KeyError: "['Sex'] not in index"

In [24]:
y = hr_trim[['Pay Rate']]
X = hr_trim.drop([['Pay Rate', 'Performance Score_90-day meets', 'Employee Source_Word of Mouth', 'Sex_Female']], axis=1)

TypeError: unhashable type: 'list'